### ISSUE TITLE
Fiio K11

### ISSUE THREAD

**Issue by StephenC-ahh** [GioF71/tidal-connect#202]
Do you know if this DAC is supported?

**Comment by StephenC-ahh** [comment]
Actually ignore that - I got it working with much fettling around
`./configure.sh -n "K11" -o`
`docker-compose up -d --force-recreate`

**Comment by GioF71** [comment]
Hello, can you post your working .env file?
Thank you!

**Comment by StephenC-ahh** [comment]
it only has one entry
CARD_NAME=K11

**Comment by StephenC-ahh** [comment]
[logs.txt](https://github.com/user-attachments/files/17111791/logs.txt)
copy of docker logs if its any use

**Comment by GioF71** [comment]
Does software volume work? I mean, from within the Tidal app, if you change the volume slider when using the Tidal Connect device, does the volume change? From the logs, it seems everything is ok and softvol should be working. Thank you again.

**Comment by StephenC-ahh** [comment]
yeah it all works. Big appreciation for your work on this

**Comment by GioF71** [comment]
> yeah it all works. Big appreciation for your work on this

Ok thank you again, I will push a change to the repo probably tonight, with the sample env file and updated documentation!
